#!/bin/sh

if [ -z "$1" ];then
  echo "needs a comment"
  exit 1
fi

git checkout expo
sleep 1
git add .
sleep 1
git commit -m "bugfix"
sleep 1
git push
sleep 1
git checkout detached
sleep 1
git merge -m "merge" expo
sleep 1
git reset --soft origin/expo
sleep 1
git commit -m "detached"
sleep 1
git push -f
