const baseDepartures = () => Promise.resolve(
    [{savedNumber:'VUPE0', stop_date_time: {base_departure_date_time: '05:23'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'05:23',
        stops:['Boigneville','Buno‑Gironville','Maisse','Boutigny','La Ferté‑Alais','Ballancourt','Mennecy','Moulin‑Galant','Corbeil‑Essonnes','Le Bras‑de‑Fer','Evry‑Courcouronnes','Orangis‑Bois‑de‑l\'Epine','Grigny‑Centre','Juvisy','Vigneux‑sur‑Seine','Villeneuve‑St‑Georges','Maisons‑Alfort‑Alfortv.','Gare‑de‑Lyon‑RER‑D','Châtelet‑les‑Halles','Gare‑du‑Nord','Stade‑France‑St‑Denis','St‑Denis','Pierrefitte‑Stains','Garges‑Sarcelles','Villiers‑le‑Bel‑Gonesse'],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE1', stop_date_time: {base_departure_date_time: '05:53'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'05:53',
        stops:['Boigneville','Buno‑Gironville','Maisse','Boutigny','La Ferté‑Alais','Ballancourt','Mennecy','Moulin‑Galant','Corbeil‑Essonnes','Le Bras‑de‑Fer','Evry‑Courcouronnes','Orangis‑Bois‑de‑l\'Epine','Grigny‑Centre','Juvisy','Vigneux‑sur‑Seine','Villeneuve‑St‑Georges','Maisons‑Alfort‑Alfortv.','Gare‑de‑Lyon‑RER‑D','Châtelet‑les‑Halles','Gare‑du‑Nord','Stade‑France‑St‑Denis'],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE2', stop_date_time: {base_departure_date_time: '06:23'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'06:23',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE3', stop_date_time: {base_departure_date_time: '06:38'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'06:38',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE4', stop_date_time: {base_departure_date_time: '06:53'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'06:53',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE5', stop_date_time: {base_departure_date_time: '07:08'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'07:08',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE6', stop_date_time: {base_departure_date_time: '07:23'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'07:23',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE7', stop_date_time: {base_departure_date_time: '07:38'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'07:38',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE8', stop_date_time: {base_departure_date_time: '07:53'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'07:53',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'
    }},{savedNumber:'VUPE9', stop_date_time: {base_departure_date_time: '08:23'},
        dataToDisplay:{mode:'RER',
        name:'D',
        direction:'Villiers‑Le‑Bel‑Gonesse',
        number:'VUPE',
        time:'08:23',
        stops:[],
        fontColor:'FFFFFF',
        color:'5E9620'}}])

export default {baseDepartures, feed:[], metadata: {features: ['departures'], everywhere: false,
        ratings:{relevancy: 0, reliability: 5, sustainability: 5, efficiency: 5}}}