import fake from './fake'
import flightRadar from './flightRadar'
import garesSncf from './garesSncf'
import horairesInfoTrafic from './horairesInfoTrafic'
import inMemory from './inMemory'
import lignesDazur from './lignesDazur'
import stas from './stas'
import liveMap from './liveMap'
import nouveauSncf from './nouveauSncf'
import raildar from './raildar'
import sncfApi from './sncfApi'
import terSncf from './terSncf'
import transilien from './transilien'
import vianavigo from './vianavigo'

export default { fake, flightRadar, garesSncf, horairesInfoTrafic, inMemory, lignesDazur, liveMap, nouveauSncf, raildar, sncfApi, stas, terSncf, transilien, vianavigo }